version: "3.9"
services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe
      MYSQL_DATABASE: _internal
    volumes:
      - mariadb_data:/var/lib/mysql

  redis-cache:
    image: redis:6-alpine
  redis-queue:
    image: redis:6-alpine
  redis-socketio:
    image: redis:6-alpine

  backend:
    image: frappe/erpnext:v14
    depends_on: [mariadb, redis-cache, redis-queue, redis-socketio]
    environment:
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  nginx:
    image: frappe/erpnext-nginx:v14
    ports:
      - "8088:8080"
    depends_on: [backend]
    volumes:
      - sites:/usr/share/nginx/html/sites

volumes:
  mariadb_data:
  sites:
